import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Heart, Layers, Search, ShoppingCart, User } from 'lucide-react';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

function Header() {
	return (
		<header className="container px-4 md:px-6 mx-auto max-w-7xl sticky top-0 z-50 w-full bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
			<div className="container flex h-16 items-center">
				{/* Logo */}
				<div className="mr-4 flex items-center">
					<a href="/" className="flex items-center space-x-2">
						<Layers className="h-6 w-6 mr-2" />
						<span className="font-bold text-xl">Varoboba</span>
					</a>
				</div>

				{/* Search */}
				<div className="flex-1 md:flex md:justify-center">
					<div className="relative w-full max-w-md">
						<div className="flex h-10 items-center rounded-md border bg-background px-3 text-sm ring-offset-background">
							<input
								className="flex-1 bg-transparent py-2 outline-none placeholder:text-muted-foreground"
								placeholder="Rechercher des produits..."
								type="search"
							/>
							<button className="ml-2 flex h-7 w-7 items-center justify-center rounded-md bg-primary text-primary-foreground hover:bg-primary/90">
								<Search className="h-4 w-4" />
							</button>
						</div>
					</div>
				</div>

				{/* User actions */}
				<div className="flex items-center space-x-4">
					{/* Cart */}
					<button className="relative inline-flex h-9 w-9 items-center justify-center rounded-md border bg-background text-sm font-medium hover:bg-accent hover:text-accent-foreground">
						<ShoppingCart className="h-4 w-4" />
						<span className="absolute -right-1 -top-1 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-[10px] text-primary-foreground">
							2
						</span>
					</button>

					{/* Favorites */}
					<button className="relative inline-flex h-9 w-9 items-center justify-center rounded-md border bg-background text-sm font-medium hover:bg-accent hover:text-accent-foreground">
						<Heart className="h-4 w-4" />
						<span className="absolute -right-1 -top-1 flex h-4 w-4 items-center justify-center rounded-full bg-primary text-[10px] text-primary-foreground">
							3
						</span>
					</button>

					{/* User profile */}
					<button className="inline-flex h-9 w-9 items-center justify-center overflow-hidden rounded-full border bg-background hover:bg-accent hover:text-accent-foreground">
						<span className="flex items-center justify-center">
							<User className="h-4 w-4" />
						</span>
					</button>
				</div>
			</div>
		</header>
	);
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	);
}
